version: 2.1

workflows:
  install-and-checkstyle:
    jobs:
      - install
      - checkstyle

jobs:
  install:
    working_directory: ~/liftwizard
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout

      - restore_cache:
          # restore the saved cache after the first run or if `pom.xml` has changed
          # https://circleci.com/docs/2.0/caching/
          key: liftwizard-{{ checksum "pom.xml" }}

      - run: ./mvnw de.qaware.maven:go-offline-maven-plugin:1.2.4:resolve-dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: liftwizard-{{ checksum "pom.xml" }}

      - run: ./mvnw install --offline --threads 2C

      # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  checkstyle:
    working_directory: ~/liftwizard
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout

      - restore_cache:
          # restore the saved cache after the first run or if `pom.xml` has changed
          # https://circleci.com/docs/2.0/caching/
          key: liftwizard-{{ checksum "pom.xml" }}

      - run: ./mvnw de.qaware.maven:go-offline-maven-plugin:1.2.4:resolve-dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: liftwizard-{{ checksum "pom.xml" }}

      - run: ./mvnw checkstyle:check --offline --threads 2C
