[tools]
java = "temurin-21.0.9+10.0.LTS"
just = "1.46.0"
maven = "3.9.12"
mvnd = "1.0.3"
node = "24.13.0"
"npm:markdownlint-cli" = "0.45.0"
"npm:strip-ansi-cli" = "4.0.0"

[tool_alias]
mvnd = "asdf:https://github.com/joschi/asdf-mvnd"

[env]
TERM = 'xterm-256color'
