name: Build, test, and lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: build-and-test-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v4
        with:
          java-version-file: .tool-versions
          distribution: oracle

      - run: ./mvnw verify --activate-profiles 'maven-enforcer-plugin,maven-dependency-plugin'

      - run: rm -rf ~/.m2/repository/io/liftwizard
        name: 'Clean Maven cache'

  checkstyle-semantics:
    name: Checkstyle Semantics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/cache@v4
        with:
          key: checkstyle-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v4
        with:
          java-version-file: .tool-versions
          distribution: oracle

      - run: ./mvnw install --projects liftwizard-utility/liftwizard-checkstyle
        name: 'Install liftwizard-checkstyle module'

      - run: ./mvnw checkstyle:check --activate-profiles 'checkstyle-semantics' -Dcheckstyle.failOnViolation=false -Dcheckstyle.failsOnError=false -Dcheckstyle.output.format=xml
        name: 'Produce Checkstyle XML: Semantics'

      - uses: lcollins/checkstyle-github-action@v2.0.0
        name: 'Checkstyle GitHub Annotations: Semantics'
        with:
          path: '**/checkstyle-result.xml'
          name: 'Checkstyle GitHub Annotations: Semantics'

      - run: rm -rf ~/.m2/repository/io/liftwizard
        name: 'Clean Maven cache'

  checkstyle-formatting:
    name: Checkstyle Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/cache@v4
        with:
          key: checkstyle-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v4
        with:
          java-version-file: .tool-versions
          distribution: oracle

      - run: ./mvnw install --projects liftwizard-utility/liftwizard-checkstyle
        name: 'Install liftwizard-checkstyle module'

      - run: ./mvnw checkstyle:check --activate-profiles 'checkstyle-formatting' -Dcheckstyle.failOnViolation=false -Dcheckstyle.failsOnError=false -Dcheckstyle.output.format=xml
        name: 'Produce Checkstyle XML: Formatting'

      - uses: lcollins/checkstyle-github-action@v2.0.0
        name: 'Checkstyle GitHub Annotations: Formatting'
        with:
          path: '**/checkstyle-result.xml'
          name: 'Checkstyle GitHub Annotations: Formatting'

      - run: rm -rf ~/.m2/repository/io/liftwizard
        name: 'Clean Maven cache'
