# Based on https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository

on:
    push:
        tags:
            - "*"

jobs:
    publish:
        permissions:
            id-token: write
            attestations: write

        name: publish to Maven Central
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-java@v5
              with:
                  java-version: 17.0.10
                  distribution: oracle
                  server-id: central
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

            - uses: jdx/mise-action@v3

            - name: Publish package
              run: just deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
                  MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

            - uses: actions/attest-build-provenance@v3
              with:
                  subject-path: "**/target/*.jar"
