# Based on https://github.com/testingisdocumenting/znai/blob/master/.github/workflows/documentation-deploy.yaml

name: Deploy Znai docs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-znai-docs:
    name: Generate Znai docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: znai-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v4
        with:
          java-version-file: .tool-versions
          distribution: oracle

      - name: Set up grahpviz
        run: sudo apt-get install graphviz

      - run: ./mvnw package --projects docs --also-make --activate-profiles 'znai-maven-plugin'

      - name: Create deploy directory
        if: github.event_name == 'push'
        run: |
          mkdir ./deploy
          mv ./docs/target/docs/ ./deploy/
          cp ./docs/index.html   ./deploy/

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: liftwizard.io
          force_orphan: true
          commit_message: "[skip ci] deploy to gh-pages"

      - run: rm -rf ~/.m2/repository/io/liftwizard
        name: 'Clean Maven cache'
